version: "3.9"
services:
  life-support-service-development:
    build:
      context: .
      target: docker-development
    ports:
      - ${APP_PORT}:${APP_PORT}             # APP_PORT from the file .env
      - '9229:9229'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: npm run start:dev
    networks:
      - ci-bdfp-bff-network-development

networks:
  ci-bdfp-bff-network-development:
    driver: bridge
