### Open a new global cart
POST http://localhost:3001/cart/2/openGlobalCart
Content-Type: application/json

{
  "customersCount": 4
}


### Get info about a table cart
GET http://localhost:3001/cart/2
Content-Type: application/json


### Create new user cart
PUT http://localhost:3001/cart/2/createUserCart
Content-Type: application/json

{}

### Add new menu item
PUT http://localhost:3001/cart/2/addItemToUserCart/1
Content-Type: application/json

{
  "id_item": "636523483d479f4112b55e4e"
}

### Remove menu item
PUT http://localhost:3001/cart/2/removeItemToUserCart/1
Content-Type: application/json

{
  "id_item": "636523483d479f4112b55e4e"
}

### Validate all order and pass command
POST http://localhost:3001/cart/2/validateGlobalOrder
Content-Type: application/json

{}

### Delete global cart when the clients leave table
POST http://localhost:3001/cart/2/deleteGlobalCart
Content-Type: application/json

{}




