### Open a new global cart
POST http://localhost:3001/cart/2/openGlobalCart
Content-Type: application/json

{
  "customersCount": 4
}


### Get info about a table cart
GET http://localhost:3001/cart/2
Content-Type: application/json


### Create new user cart
PUT http://localhost:3001/cart/2/createUserCart
Content-Type: application/json

{}

### Add new menu item
PUT http://localhost:3001/cart/2/addItemToUserCart/2
Content-Type: application/json

{
  "id_item": "6378bcf0cbb19b2a35878dbd"
}

### Remove menu item
PUT http://localhost:3001/cart/2/removeItemToUserCart/2
Content-Type: application/json

{
  "id_item": "6378bcf0cbb19b2a35878dbd"
}

### Validate all order and pass command
POST http://localhost:3001/cart/2/validateGlobalOrder
Content-Type: application/json

{}

### Delete global cart when the clients leave table
DELETE http://localhost:3001/cart/2/deleteGlobalCart
Content-Type: application/json

{}


### Get one billing
GET http://localhost:3001/billing/6378ba8db209010666d1f85e
Content-Type: application/json

### Pay for all
POST http://localhost:3001/billing/6378ba8db209010666d1f85e/pay-for-all
Content-Type: application/json

{}

### Pay for one
POST http://localhost:3001/billing/6378ba8db209010666d1f85e/0/pay-for-one
Content-Type: application/json

{}
