version: "3.8"

networks:
  nestjs-restaurant-network:
    driver: bridge

services:
  database:
    image: "mongo:4.4.15"
    restart: always
    ports:
      - "27017:27017"
    networks:
      - nestjs-restaurant-network

  dining-service:
    build:
      context: ./dining-service
      dockerfile: ./Dockerfile
      target: production
    restart: always
    ports:
      - "3001:3000"
    environment:
      - APP_PORT=3000
      - APP_NAME=dining-service
      - MONGODB_HOST=database
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=dining-db
      - SWAGGERUI_PATH=doc/dining
      - SWAGGERUI_TITLE=MicroService Restaurant - Dining Service
      - SWAGGERUI_DESCRIPTION=Dining Service Open API definition
      - MENU_SERVICE_URL_WITH_PORT=menu-service:3000
      - KITCHEN_SERVICE_URL_WITH_PORT=kitchen-service:3000
    depends_on:
      - database
    networks:
      - nestjs-restaurant-network

  menu-service:
    build:
      context: ./menu-service
      dockerfile: ./Dockerfile
      target: production
    restart: always
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=3000
      - APP_NAME=menu-service
      - MONGODB_HOST=database
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=menu-db
      - SWAGGERUI_PATH=doc/menus
      - SWAGGERUI_TITLE=Micro-Service Restaurant - Menu Service
      - SWAGGERUI_DESCRIPTION=Menu Service Open API definition
    depends_on:
      - database
    networks:
      - nestjs-restaurant-network

  kitchen-service:
    build:
      context: ./kitchen-service
      dockerfile: ./Dockerfile
      target: production
    restart: always
    ports:
      - "3002:3000"
    environment:
      - APP_PORT=3000
      - APP_NAME=kitchen-service
      - MONGODB_HOST=database
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=kitchen-db
      - SWAGGERUI_PATH=doc/kitchen
      - SWAGGERUI_TITLE=Micro-Service Restaurant - Kitchen Service
      - SWAGGERUI_DESCRIPTION=Kitchen Service Open API definition
      - DINING_SERVICE_URL_WITH_PORT=dining-service:3000
    depends_on:
      - database
    networks:
      - nestjs-restaurant-network

  gateway:
    build:
      context: ./gateway
      dockerfile: ./Dockerfile
      target: production
    restart: always
    ports:
      - "9500:3000"
    environment:
      - APP_PORT=3000
      - APP_NAME=gateway
      - MENU_SERVICE_URL_WITH_PORT=menu-service:3000
      - DINING_SERVICE_URL_WITH_PORT=dining-service:3000
      - KITCHEN_SERVICE_URL_WITH_PORT=kitchen-service:3000
    depends_on:
      - database
    networks:
      - nestjs-restaurant-network

