version: "3"

services:
  menu-service:
    image: "restaurant/menu-service"
    restart: always
    ports:
      - 3000:8080
    depends_on:
      - mongo_db_menu
  mongo_db_menu:
    image: ${MONGO_IMAGE}
    restart: always
    ports:
      - 27017:27017
