### Open a new global cart
POST http://localhost:3001/cart/2/openGlobalCart
Content-Type: application/json

{}


### Close a new global cart
POST http://localhost:3001/cart/1/closeGlobalCart
Content-Type: application/json

{}

### Create new user cart
PUT http://localhost:3001/cart/2/createUserCart
Content-Type: application/json

{}

### Add new menu item
PUT http://localhost:3001/cart/1/addItemToUserCart/0
Content-Type: application/json

{
  "id_item": "635f9d8211ff2020fb994369"
}

### Remove menu item
PUT http://localhost:3001/cart/1/removeItemToUserCart/0
Content-Type: application/json

{
  "id_item": "635f9d8211ff2020fb994369"
}




